services:
  - type: web
    name: 24pex-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_API_ID
        value: "36539152"
      - key: TELEGRAM_API_HASH
        value: "bf6c8f3ce3171efad7c80d2f72176f23"
      - key: TELEGRAM_GROUP_IDS
        value: "-1003778567819,-1003632439896,-5292682098"
      - key: INDONESIAN_GROUP_ID
        value: "-5292682098"
      - key: BOT_PORT
        value: "10000"
      - key: SESSION_STRING
        sync: false
